app:
  refresh: refresh
    
server:
  port: 0

spring:
  rabbitmq:
    host: 10.9.237.146
    port: 5672
    username: admin
    password: admin
    virtual-host: /test

  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
    
swagger:
  enabled: true